### ISSUE TITLE
GL_LINES

### ISSUE THREAD

**Issue by randeye** [dwmkerr/sharpgl#101]
I'm new to SharpGL and trying to learn how things work. I'm trying to simply draw a line using two Vertex points and GL_LINES. I'm seeing my line but it is very faint. I tried setting the color and also implementing a basic light (GL_LIGHT0) but nothing makes the line brighter. Can someone tell me how to brighten the line or have some code I could look at?
Thanks

**Comment by randeye** [comment]
I knew I'd find the answer minutes after posting. I had GL_TEXTURE_2D enabled. Disabling it made the line bright :)

**Comment by bitzhuwei** [comment]
You can close this issue as you found the answer.

**Comment by MarioFoerster** [comment]
Hi Frank,

anbei ein erster Entwurf für die Leistungsbeschreibung Version 2 (und auch Version 3 am Ende des Dokuments) …

Bis 10. konnte ich soweit alle Aufgaben einigermaßen vollständig definieren, die kann ich an Patrick weitergeben und mir ein Angebot einholen. Bei den restlichen Punkten müssen wir erst ein exaktes Konzept definieren, sonst kann man kein wirkliches Angebot machen. Ich habe einfach mal alles aufgeschrieben, was mir an Aufgaben so eingefallen ist. Sicherlich kann man noch einiges in Version 3 schieben oder auch streichen. Die Liste ist daher auch mehr ein Entwurf …

Was kann ich an Patrick schon weitergeben und welche Punkte soll ich aussortieren? Hast du noch was, was mit auf die Liste soll? Für die Überarbeitung der Touch-Bedienung (Punkt 12.) sammle ich gerade aller Ideen zusammen. Da entsteht grade eine kleine Liste, aber ich glaube da müssen wir uns richtig zusammensetzen und ausknobeln …

Gruß Mario

Von: Dave Kerr<mailto:notifications@github.com>
Gesendet: ‎Mittwoch‎, ‎27‎. ‎Mai‎ ‎2015 ‎00‎:‎42
An: dwmkerr/sharpgl<mailto:sharpgl@noreply.github.com>


Closed #101<https://github.com/dwmkerr/sharpgl/issues/101>.

**Comment by MarioFoerster** [comment]
Hi Dave …

think sent some “wrong” mail to you … Just delete it … Sorry 😊

Best regards from one of your german SharpGL user …

Mario

Von: Dave Kerr<mailto:notifications@github.com>
Gesendet: ‎Mittwoch‎, ‎27‎. ‎Mai‎ ‎2015 ‎00‎:‎42
An: dwmkerr/sharpgl<mailto:sharpgl@noreply.github.com>


Closed #101<https://github.com/dwmkerr/sharpgl/issues/101>.
