### ISSUE TITLE
Fontsize change doesn't bring any results in DrawText3D

### ISSUE THREAD

**Issue by kolorowezworki** [dwmkerr/sharpgl#148]
DrawText3d method takes a fontSize argument which seems to be not working. How to change font size using this method?

**Comment by GianlucaGrotto** [comment]
I have the same problem, is there any one can help to solve?

**Comment by kolorowezworki** [comment]
I don't use SharpGL anymore. Offscreen rendering in C++ and texture transfer are bringing better performance results

**Comment by GianlucaGrotto** [comment]
ok, I partialy solved scaling the text, but in not so satisfing.

**Comment by dwmkerr** [comment]
I'm looking at this now

**Comment by dwmkerr** [comment]
OK I've double checked - the font height is passed to the `CreateFont` function, but the underlying `wglUseFontOutlines` function doesn't actually care about the size of the font, it just creates the geometry. The _only_ way to scale the font is by performing a scale transformation.

I've removed the parameter and updated the sampless.

**Comment by GianlucaGrotto** [comment]
Thks

Il Ven 10 Lug 2020, 18:16 Dave Kerr <notifications@github.com> ha scritto:

**Comment by GianlucaGrotto** [comment]
is there a way to get the region size of the text?
