### ISSUE TITLE
new version 2.4.1.1 dont include SceneGraph

### ISSUE THREAD

**Issue by pk2016** [dwmkerr/sharpgl#159]

**Comment by dwmkerr** [comment]
Well spotted, I'll fix this and update. Thanks @pk2016!

I'll also update the README with the right links (it seems there's a 2.7 version hanging around as well, so some cleanup is needed)

**Comment by nzain** [comment]
After upgrading to 2.4.1.1 my good old project doesn't compile anymore. One of the first compiler errors I see in VS is

    Error	CS0234	The type or namespace name 'SceneGraph' does not exist in the namespace 
    'SharpGL' (are you missing an assembly reference?)

which seems to be related to this issue. Why is it closed? How is this problem resolved?

**Comment by dwmkerr** [comment]
Hi @pk2016 @nzain - I've fixed the build so that a `SharpGL.SceneGraph` package is created. You can now add a reference to this and it will solve your issue. Hope that helps!

**Comment by nzain** [comment]
When will this change make it into a nuget package? This project does not
have frequent releases (which is perfectly fine), but it's not so nice when
the latest nuget doesn't work :-)

Dave Kerr <notifications@github.com> schrieb am So., 30. Juni 2019, 10:34:

**Comment by dwmkerr** [comment]
It's published now, 2.4.1.2:

https://github.com/dwmkerr/sharpgl#getting-started

You can see the official latest versions in the link above, which I've put
into a table for easy reference!

**Comment by nzain** [comment]
Great to hear! Thank you for the quick action. Thumbs up :-)

Dave Kerr <notifications@github.com> schrieb am So., 30. Juni 2019, 11:24:

**Comment by dwmkerr** [comment]
No worries!
