### ISSUE TITLE
Missing methods and constants?

### ISSUE THREAD

**Issue by jochemgeussens** [dwmkerr/sharpgl#34]
Dear Sir

I'd like to let you know that I've found a couple of missing GL constants and methods while using SharpGL. I think there might be a need to do a big update regarding the implementation of the newer constants and method calls. Most of the ones I've found so far are neglectable for me, but VAO sounds quite promising, so it should be available in SharpGL. I'll continue updating this list as I find more of them.

Constants:
https://www.opengl.org/sdk/docs/man3/xhtml/glBindBuffer.xml
- GL_COPY_READ_BUFFER = 36662
- GL_COPY_WRITE_BUFFER = 36663
- GL_UNIFORM_BUFFER = 35345
- GL_HALF_FLOAT = 5131
- Int_2_10_10_10_Rev = 36255
- GL_COLOR_ATTACHMENT0 = 36065

Methods:
- glVertexAttribLPointer : http://www.opengl.org/sdk/docs/man/html/glVertexAttribPointer.xhtml
- glDrawElementsBaseVertex, required for using VAO's http://www.opengl.org/sdk/docs/man/html/glDrawElementsBaseVertex.xhtml
- glMapBufferRange: https://www.opengl.org/sdk/docs/man3/xhtml/glMapBufferRange.xml

Kind regards,
Jochem

**Comment by dwmkerr** [comment]
Hi @jochemgeussens just a heads up I'm about to release 2.4, once this is done I'll be looking into this issue, I've been working on the performances of buffers and arrays. I'd be interested to get your thoughts on the changes once they're done.

**Comment by dwmkerr** [comment]
OK the full details.

`GL_COPY_READ_BUFFER` and `GL_COPY_WRITE_BUFFER`. Defined as part of `ARB_copy_buffer`, incorrectly named `EXT_copy_buffer` as part of OpenGL 3.1. Issue #80 deals with this.

`GL_UNIFORM_BUFFER` also missing as part of OpenGL 3.1. Issue #80 deals with this.

`GL_HALF_FLOAT` is missing as well. Should be part of OpenGL 3.0, see `NV_half_float` and  `EXT_half_float_pixel`. Issue #81 deals with this.

`Int_2_10_10_10_Rev` missing from OpenGL 3.3 implementation. Issue #82 deals with this.

`GL_COLOR_ATTACHMENT0`. Currently named `GL_COLOR_ATTACHMENT0_EXT` in the code, will be fixed as part of #81.

`glVertexAttribLPointer` missing as part of OpenGL 4.1 Issue #83.

`glDrawElementsBaseVertex` issue #84.

`glMapBufferRange` see #81.

Essentially, I will check each extension then close this issue.

**Comment by dwmkerr** [comment]
All fixed.
