### ISSUE TITLE
SharpGL not listed for VS 2013

### ISSUE THREAD

**Issue by dwmkerr** [dwmkerr/sharpgl#42]
It seems that sharpgl isn't listed for VS2013, this must be solved ASAP

https://sharpgl.codeplex.com/discussions/548783
http://visualstudiogallery.msdn.microsoft.com/b61cc443-4790-42b7-b7ab-2691119667d2/view/Discussions/0

**Comment by robinsedlaczek** [comment]
Just for info: NuGet packages are listed in Visual Studio 2015. WPF, Core and WinForms are there. Extensions aren't.

**Comment by dwmkerr** [comment]
Resolved with #71, Visual Studio 2015 support tracked with issue #77 for 2.5
