### ISSUE TITLE
Include SetLastError = true into all winapi functions

### ISSUE THREAD

**Issue by akastalker** [dwmkerr/sharpgl#43]
If every imported function (that potentially can fail) in SharpGL.Win32 namespace will be changed from:
```c#
        [DllImport(OpenGL32)]
        public static extern IntPtr wglCreateContext(IntPtr hdc);
```
to:
```c#
        [DllImport(OpenGL32, SetLastError = true)]
        public static extern IntPtr wglCreateContext(IntPtr hdc);
```
, user can actually get what was wrong with the his call, if it fails, just by calling System.Runtime.InteropServices.Marshal.GetLastWin32Error() or better - by creating and\or throwing System.ComponentModel.Win32Exception().

Without SetLastError, trying to call GetLastWin32Error() after obviously failed winapi call (it returned zero) returns error code 0 ("The operation completed successfully"), as if no error occured.

See remarks section on: http://msdn.microsoft.com/en-us/library/system.runtime.interopservices.marshal.getlastwin32error%28v=vs.100%29.aspx

**Comment by dwmkerr** [comment]
Work completed. Will be released as part of 2.4
