### ISSUE TITLE
Callback before GL context destroyed?

### ISSUE THREAD

**Issue by afinetapestry** [dwmkerr/sharpgl#45]
Is there any way I could get a callback right before the GL context is torn down? I need to clean up a lot of GL objects and obviously this cannot be done if the context no longer exists.

It seems WPF offers no way of binding an event to be executed before the control is destroyed and the WPF OpenGLControl has Initialized and Draw but not Destroyed. Would this be possible?

**Comment by dwmkerr** [comment]
Hi @afinetapestry,

I think you will have to listen for the controls `UnLoaded` event. This will be called before the control is removed from the visual tree. WPF user controls don't actually have a 'destroy' event so it is up to the application to decide how to manage the lifecycle of resources it uses. Using `UnLoaded` will be fine, you will still be able to access the OpenGL instance on the control and use that for your cleanup.
